src/Webbook/MainBundle/Entity/Book.php
<?php

namespace Webbook\MainBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use JMS\Serializer\Annotation\Exclude;
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;
use JMS\Serializer\Annotation\SerializedName;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints\Date;

/**
 * Book
 *
 * @ORM\Table(name="book")
 * @ORM\Entity(repositoryClass="Webbook\MainBundle\Repository\BookRepository")
 * @ExclusionPolicy("all")
 */
class Book
{
    use ORMBehaviors\Blameable\Blameable;
    use ORMBehaviors\Timestampable\Timestampable;
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Groups({"show"})
     * @Expose
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     * @Groups({"show"})
     * @Expose
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="token", type="string", length=255, nullable=false, unique=true)
     * @Expose
     */
    private $token;

    /**
     * @ORM\ManyToOne(targetEntity="Webbook\MainBundle\Entity\Category")
     * @Serializer\Expose(true)
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity="Webbook\MainBundle\Entity\BookBlock",mappedBy="book",cascade={"persist","remove"},orphanRemoval=true, fetch="EAGER")
     * @ORM\OrderBy({"position" = "ASC"})
     */
    private $blocks;

    /**
     * @ORM\ManyToMany(targetEntity="Core\UserBundle\Entity\User",inversedBy="hasBook")
     * @ORM\JoinTable(name="book_has_author")
     * @Groups({"show"})
     * @SerializedName("authors")
     * @Expose
     */
    private $mainAuthors;

    /**
     * @var string
     * @ORM\Column(name="description",type="text")
     * @Expose
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="Webbook\MainBundle\Entity\BookEdition",mappedBy="book",cascade={"persist","remove"},orphanRemoval=true)
     * @ORM\OrderBy({"createdAt" = "ASC"})
     */
    private $editions;

    /**
     * @ORM\OneToMany(targetEntity="Webbook\MainBundle\Entity\Media",mappedBy="book",cascade={"persist","remove"},orphanRemoval=true)
     * @Groups({"show"})
     * @Expose
     */
    private $images;

    /**
     * @var bool
     * @ORM\Column(name="published",type="boolean")
     * @Exclude
     */
    private $published;
    /**
     * @var bool
     * @ORM\Column(name="published_preview",type="boolean")
     * @Exclude
     */
    private $publishedPreview;

    /**
     * @var \DateTime
     * @ORM\Column(name="publish_date",type="date",nullable=true)
     * @Expose
     */
    private $publishDate;

    /**
     * @var float
     *
     * @ORM\Column(name="price", type="float")
     * @Expose
     */
    private $price;

    /**
     * @var string
     * @ORM\Column(name="isbn",type="string")
     * @Expose
     * @SerializedName("ISBN")
     */
    private $ISBN;

    /**
     * @var string
     *
     * @ORM\Column(name="language", type="string", length=255)
     * @Groups({"show"})
     * @Expose
     */
    private $language;

    /**
     * @ORM\OneToMany(targetEntity="Webbook\MainBundle\Entity\BookReview" , mappedBy="book", cascade={"remove"})
     * @Expose
     */
    private $reviews;

    /**
     * Book constructor.
     */
    public function __construct(){
        $this->blocks=new ArrayCollection();
        $this->editions=new ArrayCollection();
        $this->images=new ArrayCollection();
        $this->reviews= new ArrayCollection();
        $this->published=false;
        $this->publishedPreview=false;
        $this->token = sha1(rand(11111, 99999).date('d-m-Y').time());
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set titre
     *
     * @param string $title
     *
     * @return Book
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set token
     *
     * @param string $token
     *
     * @return Book
     */
    public function setToken($token)
    {
        $this->token = $token;

        return $this;
    }

    /**
     * Get token
     *
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

	public function __toString(){
		return $this->token;
	}


    /**
     * @return Category
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param mixed $category
     */
    public function setCategory($category)
    {
        $this->category = $category;
    }

    /**
     * @return bool
     */
    public function getPublished()
    {
        return $this->published;
    }

    /**
     * @param bool $published
     */
    public function setPublished($published)
    {
        $this->published = $published;
    }

    /**
     * @return mixed
     */
    public function getBlocks()
    {
        return $this->blocks;
    }

    /**
     * @return mixed
     */
    public function getUnderBlock()
    {
        $res=new ArrayCollection();
        foreach ($this->blocks as $block)
            if($block->getLevel()==0)
                $res->add($block);

        // sorting by position
        $iterator = $res->getIterator();
        $iterator->uasort(function ($a, $b) {
            return ($a->getPosition() > $b->getPosition()) ? 1 : -1;
        });
        $res = new ArrayCollection(iterator_to_array($iterator));
        return $res;
    }

    /**
     * @param mixed $blocks
     * @return $this
     */
    public function setBlocks($blocks)
    {
        $this->blocks = $blocks;
        return $this;
    }

    /**
     * @param BookBlock $block
     */
    public function addBlock($block){
        $this->blocks->add($block);
        $block->setBook($this);
    }

    /**
     * @param BookBlock $child
     */
    public function removeBlock($child){
        $this->blocks->remove($this->blocks->indexOf($child));
    }


    /**
     * @return mixed
     */
    public function getMainAuthors()
    {
        return $this->mainAuthors;
    }

    /**
     * @param mixed $mainAuthors
     */
    public function setMainAuthors($mainAuthors)
    {
        $this->mainAuthors = $mainAuthors;
    }

    public function getSlug()
    {
        return self::slugify($this->title);
    }

    static public function slugify($text)
    {
        // replace non letter or digits by -
        $text = preg_replace('~[^\pL\d]+~u', '-', $text);

        // transliterate
        $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);

        // remove unwanted characters
        $text = preg_replace('~[^-\w]+~', '', $text);

        // trim
        $text = trim($text, '-');

        // remove duplicate -
        $text = preg_replace('~-+~', '-', $text);

        // lowercase
        $text = strtolower($text);

        if (empty($text)) {
            return 'n-a';
        }

        return $text;
    }

    /**
     * @return mixed
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * @param mixed $images
     */
    public function setImages($images)
    {
        $this->images = $images;
    }

    /**
     * @param Media $media
     */
    public function addImage($media)
    {
        $media->setBook($this);
        $this->images->add($media);
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * @return \DateTime
     */
    public function getPublishDate()
    {
        return $this->publishDate;
    }

    /**
     * @param \DateTime $publishDate
     */
    public function setPublishDate($publishDate)
    {
        $this->publishDate = $publishDate;
    }

    /**
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * @param float $price
     */
    public function setPrice($price)
    {
        $this->price = $price;
    }

    /**
     * @return string
     */
    public function getISBN()
    {
        return $this->ISBN;
    }

    /**
     * @param string $ISBN
     */
    public function setISBN($ISBN)
    {
        $this->ISBN = $ISBN;
    }

    /**
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * @param string $language
     */
    public function setLanguage($language)
    {
        $this->language = $language;
    }

    /**
     * @return mixed
     */
    public function getReviews()
    {
        return $this->reviews;
    }

    /**
     * @param BookReview $review
     */
    public function addReview(BookReview $review){
        $review->setBook($this);
        $this->reviews->add($review);
    }

    /**
     * @param mixed $reviews
     */
    public function setReviews($reviews)
    {
        $this->reviews = $reviews;
    }

    /**
     * @return mixed
     */
    public function getEditions()
    {
        return $this->editions;
    }

    /**
     * @param mixed $editions
     */
    public function setEditions($editions)
    {
        $this->editions = $editions;
    }

    /**
     * @param BookEdition $edition
     */
    public function addEdition($edition){
        $edition->setBook($this);
        $this->editions->add($edition);
    }


    /**
     * @return BookEdition
     */

src/Webbook/MainBundle/Resources/views/Author/all.books.html.twig
{% extends '@Main/layout.html.twig' %}

{% block title %}
    Liste des  Livres
{% endblock %}
{% block body %}
    <!-- BEGIN PAGE BASE CONTENT -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="{{ url('author_homepage') }}">Tableau de bord</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <span class="active">Liste des livres</span>
            </li>

        </ul>
    </div>
    <div class="m-heading-1 border-green m-bordered row" style="margin-bottom: 17px;">
        <h2><i class="icon-c-books"></i>
            &nbsp; Liste des livres </h2>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box red">
                <div class="portlet-body ">
                    <table class="table table-striped table-bordered datatable " cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <th class="text-center">Date Creation</th>
                            <th class="text-center">Titre</th>
                            <th class="text-center">Categorie</th>
                            <th class="text-center">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for book in books %}
                            <tr class="text-center">
                                <td >{{ book.createdAt|date('d-m-Y') }}</td>
                                <td>{{ book.title }}</td>
                                <td>{{ book.category.name }}</td>
                                <td >
                                    <a href="{{ url('author_show_book',{token:book.token}) }}" class="btn blue "><i class="fa fa-eye"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <input type="hidden" value="" id="menuSelected" data-menu="page-all-books">

{% endblock %}
{% block stylesheets %}
{% endblock %}
{% block javascripts %}
{% endblock %}

src/Webbook/MainBundle/Resources/views/Author/edit.block.html.twig
{% extends '@Main/layout.html.twig' %}
{% block title %}
    {{ version.bookBlock.book.title }} - {{ version.bookBlock.title }} - v {{ version.number }}
{% endblock %}
{% block body %}
    <!-- BEGIN PAGE BASE CONTENT -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <i class="icon-home"></i>
                <a href="{{ url('author_homepage') }}">Tableau de bord</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <i class="material-icons dp48">library_books</i>
                <a href="{{ url('author_my_books') }}">Mes livres</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="{{ url('author_show_book',{token:version.bookBlock.book.token}) }}">{{ version.bookBlock.book.title }}</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <span class="active">{{ version.bookBlock.book.title }} - {{ version.bookBlock.title }} - v {{ version.number }} </span>
            </li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            {{ form_start(form,{'attr':{'class':'blockForm'}} ) }}
            <div class="portlet box green-meadow col-md-12" style="margin-bottom: 15px">
                <div class="portlet-title">
                    <h4 class="pull-left">Contenu du bloc</h4>
                    <div class="tools">
                        <a data-placement="bottom" href="javascript:;" class="collapse" data-original-title="reduire"
                           title=""> </a>
                        <a data-placement="bottom" href="" class="fullscreen" data-original-title="plein ecran"
                           title=""> </a>
                    </div>
                </div>
                <div class="portlet-body col-md-12">
                    <div class="col-md-12" style="display: block;">

                        <div class="slidershell">
                            <div class="sliderfill progress-bar progress-bar-striped active"></div>
                            <div class="slidertrack text-center"><strong id="ps-txt"> Progression </strong></div>
                            <div class="sliderthumb"></div>
                            <div class="slidervalue">0</div>
                            {{ form_widget(form.progress,{"attr":{"class":"progress-slider","data-min":version.progress}}) }}
                        </div>
                        {{ form_widget(form.content,{"attr":{"class":"tinyMince"}}) }}
                    </div>

                    <div class="col-md-12 text-center" style="margin-top: 15px;">
                        <button type="submit" class="btn  blue "></i>Enregistrer Modification</button>
                        <button class="btn red "
                                data-url="{{ url('author_block_version_cancel',{token:version.token}) }}"
                                type="button" id="cancelVersionCreation">Annuler la version
                        </button>
                    </div>
                </div>
            </div>
            {{ form_widget(form._token) }}
            {{ form_end(form, {'render_rest': false}) }}
        </div>
    </div>
    <div id="fm-token" data-token="{{ version.token }}"></div>
    <input type="hidden" value="" id="menuSelected" data-menu="page-books">

{% endblock %}
{% block stylesheets %}
    <link type="text/css" rel="stylesheet" href="{{ asset('assets/global/plugins/tinymce/js/tinymce/skins/lightgray/skin.min.css') }}">
{% endblock %}
{% block javascripts %}
    <script type="text/javascript"
            src="{{ asset('assets/global/plugins/tinymce/js/tinymce/tinymce.min.js') }}"></script>
    <script type="text/javascript"
            src="{{ asset('assets/global/plugins/tinymce/js/tinymce/langs/fr_FR.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/pages/js/author_edit_block.js') }}"></script>
{% endblock %}

src/Webbook/MainBundle/Resources/views/Author/index.html.twig
{% extends "MainBundle::layout.html.twig" %}
{% block classBody %}page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo{% endblock %}
{% block menu %}
    {{ parent() }}
{% endblock %}
{% block body %}
    <!-- BEGIN PAGE BASE CONTENT -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <i class="icon-home"></i>
                <a >Tableau de bord</a>
            </li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light">
                <div class="portlet-body">
                    <h1>Auteur Tableau de bord !</h1>
                </div>
            </div>
        </div>
    </div>
    <input type="hidden" value="" id="menuSelected" data-menu="page-index">

{% endblock %}

src/Webbook/MainBundle/Resources/views/Author/show.book.html.twig
{% extends '@Main/layout.html.twig' %}
{% import _self as macros %}
{% block title %}
    {{ book.title }}
{% endblock %}
{% block body %}
    <!-- BEGIN PAGE BASE CONTENT -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <i class="icon-home"></i>
                <a href="{{ url('administrator_homepage') }}">Tableau de bord</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <i class="fa fa-book"></i>
                <a href="{{ url('author_my_books') }}">Mes livres</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <span class="active">{{ book.title }}</span>
            </li>


        </ul>
    </div>
    <div class="m-heading-1 border-green m-bordered row" style="margin-bottom: 17px;">
        <h2><span class="fa fa-book"></span> &nbsp; {{ book.title }} - Détails</h2>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box green-meadow">
                <div class="portlet-title">
                    <div class="caption col-md-4">
                        Information du livre
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse" data-original-title="reduire" title=""> </a>
                        <a href="" class="fullscreen" data-original-title="plein ecran" title=""> </a>
                    </div>
                </div>
                <div class="portlet-body col-md-12" style="display: block;margin-bottom: 15px">
                    <table class="table table-bordered table-hover">
                        <tbody>
                        <tr>
                            <td class="col-md-2"><label class="custom-lb">Titre </label></td>
                            <td>{{ book.title }}</td>
                        </tr>
                        <tr>
                            <td class="col-md-2"><label class="custom-lb" >Catégorie</label></td>
                            <td>{{ book.category.name }}</td>
                        </tr>
                        <tr>
                            <td class="col-md-2"><label class="custom-lb">Auteurs</label> </td>
                            <td>
                                {% for autheur in book.mainAuthors %}
                                    - {{ autheur.fullName }}<br>
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <td class="col-md-2"><label class="custom-lb" >ISBN</label></td>
                            <td>{{ book.iSBN }}</td>
                        </tr>
                        <tr>
                            <td class="col-md-2"><label class="custom-lb" >Langue</label></td>
                            <td>{{ book.language }}</td>
                        </tr>
                        <tr>
                            <td class="col-md-2"><label class="custom-lb" >Prix</label></td>
                            <td>{{ book.price }}</td>
                        </tr>
                        <tr>
                            <td class="col-md-2"><label class="custom-lb">Résumé</label></td>
                            <td>{{ book.description|raw }}</td>
                        </tr>
                        </tbody>
                    </table>
                    <div class="col-md-12 images center" >
                        {% for img in book.images %}
                            <img style="padding: 10px" src="{{ vich_uploader_asset(img,'mediaFile') }}">
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box green-meadow">
                <div class="portlet-title">
                    <h4 class="pull-left">Structure  du livre : {{ book.title }}</h4>
                    <div class="tools">
                        <a href="javascript:;" class="collapse" data-original-title="reduire" title=""> </a>
                        <a href="" class="fullscreen" data-original-title="plein ecran" title=""> </a>
                    </div>
                </div>
                <div class="portlet-body ">
                    <table class="table table-striped table-bordered  " cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <th class="col-md-5 col-sm-6 col-xs-6">Titre</th>
                            <th class="col-md-2 text-center hidden-sm hidden-xs">Dernière version Validée</th>
                            <th class="col-md-2 text-center col-sm-2 col-xs-2">Version Publiée</th>
                            <th class="col-md-3  text-center col-sm-4 col-xs-4">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% macro displayVersionBlock(blocks) %}
                            {% import _self as macros %}
                            {% for block in blocks| sortbyfield('position') %}
                                <tr {% if block.parent %}data-parent="{{ block.parent.id }}" {% endif %} class=" {% if block.level>0%} hidden{% endif %}">
                                    <td  style="overflow-x: hidden" class="col-md-5 col-sm-6 col-xs-6" data-pdl="25" data-level="{{ block.level }}">
                                        {% if block.childrens|length>0 %}
                                            <button class="btn green btn-xs btn-show-children" data-id="{{ block.id }}"><i class=" fa fa-plus"></i></button>
                                        {% endif %}
                                        {{ block.title }}
                                    </td>
                                    <td class="text-center col-md-2 hidden-sm hidden-xs">
                                        <div class="label label-success">
                                            {% if block.lastValidatedVersion is not null %}
                                                v {{ block.lastValidatedVersion.number|number_format(1,'.',',') }}
                                            {% else %}
                                                Aucune
                                            {% endif %}
                                        </div>
                                    </td>
                                    <td class="col-md-2 col-sm-2 col-xs-2 text-center">
                                        <div class="label label-success">
                                            {% if block.publishedVersion is not null %}
                                                v {{ block.publishedVersion.number|number_format(1,'.',',') }}
                                            {% else %}
                                                Aucune
                                            {% endif %}
                                        </div>
                                    </td>
                                    <td class="text-center col-md-3 col-sm-4 col-xs-4 text-center">
                                        <div class="">
                                            <a  {% if has_permission('r',block) or block.childrens|length>0  %}class="btn btn-icon-only blue" href="{{ url('author_show_block',{token:block.token} ) }}"  {% elseif block.childrens|length==0 %}class="btn btn-icon-only blue disabled-link " data-toggle="tooltip" data-title="Tu na pas la permission"{% endif %}><i class="fa fa-eye"></i> </a>
                                            {%  set version_edit = version_has_status(0,block) %}
                                            {%  set version_validate = version_has_status(1,block) %}

                                        {% if has_permission('w',block) %}
                                            {% if version_edit is not null %}
                                                {% if version_edit.createdBy==app.user %}
                                                <a class="btn btn-icon-only blue-hoki" data-toggle="tooltip" data-title="Continuer l'edition du version" href="{{ url('author_block_version_edit',{token:version_edit.token}) }}"><i class="fa fa-pencil-square-o" ></i></a>
                                                {% else%}
                                                <div class="btn-group">
                                                    <button class="btn btn-icon-only green disabled"  data-toggle="tooltip"
                                                            data-title="Il ya une autre version en cours !">
                                                            <i class="fa fa-pencil-square-o" ></i>
                                                    </button>
                                                </div>
                                                {% endif %}
                                                {% elseif version_validate is not null %}
                                                        <button data-toggle="tooltip" data-title="Encours de validation" class="btn btn-icon-only yellow disabled">
                                                            <i class="fa fa-check-square-o"></i>
                                                        </button>
                                                {% else %}
                                                    <button data-toggle="tooltip" data-title="Crée une nouvelle version"
                                                            class="btn green btn-icon-only btn-create-new-version"
                                                            data-url="{{ url('author_create_block_version',{token:block.token}) }}">
                                                        <i class="fa fa-pencil-square-o"></i>
                                                    </button>
                                                {% endif %}
                                            {% else %}
                                                <button class="btn green btn-icon-only disabled" data-toggle="tooltip"
                                                        data-title="Tu na pas la permission">
                                                    <i class="fa fa-pencil-square-o"></i>
                                                </button>
                                            {% endif %}
                                            <button {% if has_permission('d',block) %}class="btn red btn-icon-only btn-delet-block"
                                                        data-url="{{ url('author_delete_block',{token:block.token}) }}"
                                                    {% else %}
                                                        class="btn btn-icon-only red disabled "  data-toggle="tooltip"
                                                        data-title="Tu na pas la permission"
                                                    {% endif %}>
                                                <i class="fa fa-trash"></i>
                                            </button>
                                        </div>
                                    </td>
                                    {% if block.childrens|length>0 %}
                                        {{ macros.displayVersionBlock(block.childrens|sortByPosition) }}
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        {% endmacro %}
                        {{ macros.displayVersionBlock(book.underBlock|sortByPosition) }}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <input type="hidden" value="" id="menuSelected" data-menu="page-my-books">

{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('assets/global/plugins/viewer/viewer.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/global/plugins/slick/slick.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/global/plugins/slick/slick-theme.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/pages/css/book.structure.css') }}">
{% endblock %}
{% block javascripts %}
    <script type="text/javascript" src="{{ asset('assets/global/plugins/slick/slick.min.js') }}"></script>
    <script src="{{ asset('assets/global/plugins/viewer/viewer.min.js') }}"></script>
   <script type="text/javascript" src="{{ asset('assets/pages/js/author_show_book.js') }}"></script>
{% endblock %}

src/Webbook/MainBundle/Resources/views/Author/version.progression.html.twig
{% extends '@Main/layout.html.twig' %}
{% block title %}
    {{ version.bookBlock.book.title }} - {{ version.bookBlock.title }} - v {{ version.number }}
{% endblock %}
{% block body %}
    <!-- BEGIN PAGE BASE CONTENT -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <i class="icon-home"></i>
                <a href="{{ url('author_homepage') }}">Tableau de bord</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="{{ url('author_show_book',{token:version.bookBlock.book.token}) }}">{{ version.bookBlock.book.title }}</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <span class="active">progression </span>
            </li>
        </ul>
    </div>
{% endblock %}