src/Webbook/MainBundle/Entity/BookBlock.php
<?php

namespace Webbook\MainBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use JMS\Serializer\Annotation\Groups;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

/**
 * BookBlock
 *
 * @ORM\Table(name="book_block")
 * @ORM\Entity(repositoryClass="Webbook\MainBundle\Repository\BookBlockRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class BookBlock
{
    use ORMBehaviors\Blameable\Blameable;
    use ORMBehaviors\Timestampable\Timestampable;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Groups({"CandT"})
     */
    private $id;


    /**
     * @ORM\ManyToOne(targetEntity="Webbook\MainBundle\Entity\Book" , inversedBy="blocks")
     * @ORM\JoinColumn(name="book_id", referencedColumnName="id",onDelete="CASCADE")
     */
    private $book;

    /**
     * @ORM\ManyToOne(targetEntity="Webbook\MainBundle\Entity\BookBlock" , inversedBy="childrens")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id",onDelete="CASCADE")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity="Webbook\MainBundle\Entity\BookBlock" , mappedBy="parent", cascade={"remove","persist"}, orphanRemoval=true)
     * @ORM\OrderBy({"position"="ASC"})
     */
    private $childrens;

    /**
     * @var string
     * @ORM\Column(name="title", type="string",length=255)
     * @Groups({"CandT"})
     *
     */
    private $title;

    /**
     * @var int
     * @ORM\Column(name="level" , type="integer")
     */
    private $level;

    /**
     * @var int
     * @ORM\Column(name="position" , type="integer")
     */
    private $position;

    /**
     * @var string
     *
     * @ORM\Column(name="token", type="string", length=255, nullable=false, unique=true)
     */
    private $token;

    /**
     * @ORM\OneToMany(targetEntity="Webbook\MainBundle\Entity\Authorization" ,mappedBy="bookBlock", cascade={"persist", "remove"}, orphanRemoval=true)
     * @ORM\JoinColumn(referencedColumnName="id",onDelete="CASCADE")
     */
    private $authorizations;

    /**
     * @ORM\OneToMany(targetEntity="Webbook\MainBundle\Entity\Version", mappedBy="bookBlock", cascade={"remove","persist"})
     */
    private $versions;

    /**
     * @ORM\OneToOne(targetEntity="Webbook\MainBundle\Entity\BlockOptions",cascade={"persist", "remove"}, orphanRemoval=true)
     * @ORM\JoinColumn(referencedColumnName="id",onDelete="CASCADE")
     */
    private $options;

    /**
     * @ORM\OneToMany(targetEntity="Webbook\MainBundle\Entity\BlockHistoric" , mappedBy="block",cascade={"persist","remove"})
     */
    private $historics;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set token
     *
     * @param string $token
     *
     * @return BookBlock
     */
    public function setToken($token)
    {
        $this->token = $token;

        return $this;
    }

    /**
     * Get token
     *
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    public function __construct(){
        // default type bloc is set to be a title block
        $this->level=0;
        $this->position=0;
        $this->childrens=new ArrayCollection();
        $this->versions=new ArrayCollection();
        $this->options=new BlockOptions();
        $this->authorizations= new ArrayCollection();
        $this->historics=new ArrayCollection();
        $this->token = sha1(rand(11111, 99999).date('d-m-Y').time());
    }

    public function __toString(){
        return $this->title?$this->title:"zone de text";
    }

    /**
     * @return BookBlock
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * @param BookBlock $parent
     */
    public function setParent(BookBlock $parent)
    {
        if($parent){
            $this->setBook($parent->getBook());
            $this->level=$parent->getLevel()+1;
        }
        $this->parent = $parent;
    }

    public function removeParent(){
        $this->parent=null;
    }

    /**
     * @return mixed
     */
    public function getChildrens()
    {
        return $this->childrens;
    }

    /**
     * @param mixed $childrens
     */
    public function setChildrens($childrens)
    {
        $this->childrens = $childrens;
    }

    /**
     * @param mixed $child
     */
    public function addChild($child){
        $child->setParent($this);
        $child->setLevel($this->level+1);
        $this->childrens->add($child);
    }

    /**
     * @param mixed $child
     */
    public function removeChild($child){
        $this->childrens->remove($this->childrens->indexOf($child));
    }


    /**
     * @return mixed
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param mixed $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }


    /**
     * @return Book
     */
    public function getBook()
    {
        return $this->book;
    }

    /**
     * @param mixed $book
     */
    public function setBook($book)
    {
        $this->book = $book;
    }


    /**
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * @param int $level
     */
    public function setLevel($level)
    {
        $this->level = $level;
    }

    /**
     * @return mixed
     */
    public function getVersions()
    {
        return $this->versions;
    }

    /**
     * @param mixed $versions
     */
    public function setVersion($versions)
    {
        $this->versions = $versions;
    }

    /**
     * @param Version $version
     */
    public function addVersions( $version)
    {
        $this->versions->add($version);
        $version->setBookBlock($this);
    }


    /**
     * @return mixed
     */
    public function getAuthorizations()
    {
        return $this->authorizations;
    }

    /**
     * @param mixed $authorizations
     */
    public function setAuthorizations($authorizations)
    {
        /** @var Authorization $authorization */
        foreach ($authorizations as $authorization)
            $authorization->setBookBlock($this);
        $this->authorizations = $authorizations;
    }

    /**
     * @param Authorization $authorization
     */
    public function addAuthorization($authorization){
        $this->authorizations->add($authorization);
        $authorization->setBookBlock($this);
    }


    public function removeAuthorization(Authorization $authorization)
    {
        $this->authorizations->removeElement($authorization);
        $authorization->setBookBlock(null);
    }

    /**
     * @return int
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * @param int $position
     */
    public function setPosition($position)
    {
        $this->position = $position;
    }

    public static function getBlockChildren($blocks,&$result){
        if(!$blocks)
            $result=array();

        /** @var BookBlock $children */
        foreach ($blocks as $children){
            array_push($result,$children);
            self::getBlockChildren($children->getChildrens(),$result);
        }
    }


    /**
     * @return null|Version
     */
    public function getPublishedVersion()
    {
        /** @var Version $version */
        foreach ($this->versions as $version)
            if($version->getStatus()==3)return $version;
        return null;
    }

    /**
     * @return Version
     */
    public function getLastValidatedVersion(){
        $lastValidatedVersion=null;
        $lastValidatedVersionNumber=0;
        foreach ($this->versions as $version){
            if($version->getNumber()>$lastValidatedVersionNumber &&($version->getStatus()==3 or $version->getStatus()==2)){
                $lastValidatedVersion=$version;
                $lastValidatedVersionNumber=$version->getNumber();
            }
        }
        return $lastValidatedVersion;
    }

    /**
     * @return BlockOptions
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * @param mixed $options
     */
    public function setOptions($options)
    {
        $this->options = $options;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function updateLevel(){
        $this->setLevel($this->getLevelFromNest($this));
    }

    private function getLevelFromNest(BookBlock $block){
        if($block->getParent())
            return 1+$this->getLevelFromNest($block->getParent());
        else
            return 0;
    }

    public function maxDeep(){
        if($this->childrens){
            return $this->array_depth($this->childrens);
        }else
            return 0;
    }

    function array_depth($blocks) {
        $max_depth = 0;
        foreach ($blocks as $bl) {
            if ($bl->getChildrens()) {
                $depth = $this->array_depth($bl->getChildrens()) + 1;
                if ($depth > $max_depth) {
                    $max_depth = $depth;
                }
            }
        }

        return $max_depth;
    }

    /**
     * @return mixed
     */
    public function getHistorics()
    {
        return $this->historics;
    }

    /**
     * @param mixed $historics
     */
    public function setHistorics($historics)
    {
        $this->historics = $historics;
    }

    public function addHistoric(BlockHistoric $blockHistoric){
        $blockHistoric->setBlock($this);
        $this->historics->add($blockHistoric);
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @Serializer\VirtualProperty
     * @Serializer\Type("integer")
     * @Serializer\SerializedName("childrenLength")

src/Webbook/MainBundle/Controller/Validator/ValidatorController.php
<?php

namespace Webbook\MainBundle\Controller\Validator;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\DomCrawler\Crawler;
use Symfony\Component\HttpFoundation\Request;
use Webbook\MainBundle\Entity\BlockHistoric;
use Webbook\MainBundle\Entity\Version;
use Webbook\NotificationBundle\Entity\Notification;

class ValidatorController extends Controller
{
    public function indexAction()
    {
        return $this->render('@Main/Validator/index.html.twig', array(// ...
        ));
    }

    public function validationRequestsAction()
    {
        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser();
        $validationRequests = $em->getRepository('MainBundle:ValidationRequest')->findBy(['validator' => $user->getId()], ['date' => 'DESC']);

        return $this->render('@Main/Validator/validation.requests.html.twig', array(
            'validationRequests' => $validationRequests));
    }

    public function verifyVersionAction(Request $request, $token)
    {
        $em = $this->getDoctrine()->getManager();

        $validationRequest = $em->getRepository('MainBundle:ValidationRequest')->findOneBy(['token' => $token]);
        if (!$validationRequest)
            return $this->redirectToRoute('not_found');


        /** @var Version $version */
        $version = $validationRequest->getVersion();
        $bookBlock = $version->getBookBlock();

        $form = $this->createForm('Webbook\MainBundle\Form\ValidationRequestType', $validationRequest);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $version->setContent(str_replace('../../../../uploads','/uploads',$version->getContent()));
            // test if validation is done
            if ($validationRequest->getProgress() == 100) {

                $test = $this->verifyFigureAndTable($version->getContent());
                if ($test === true) {
                    $historic = new BlockHistoric();
                    $historic->setMessage("Fin de validation de version numéro " . $version->getNumber() . " par " . $this->getUser()->getFullName());
                    $bookBlock->addHistoric($historic);
                    $em->persist($bookBlock);
                    $version->setStatus(2);
                    $em->persist($version);
                    $superAdmin = $em->getRepository('UserBundle:User')->findByRoles(['ROLE_ADMINISTRATOR', 'ROLE_SUPER_ADMIN']);
                    $allConcernedUser = array_merge($superAdmin, $bookBlock->getBook()->getMainAuthors()->toArray());
                    foreach ($allConcernedUser as $user) {
                        $notif = new Notification();
                        $notif->setMessage("Une nouvelle version du bloc " . $bookBlock->getTitle() . " de livre  "
                            . $bookBlock->getBook()->getTitle() . " a été validé");
                        $notif->setIcon('fa-check-square-o');
                        if (in_array('ROLE_AUTHOR', $user->getRoles()))
                            $notif->setUrl($this->generateUrl('author_show_book', ['token' => $bookBlock->getBook()->getToken()]));
                        else
                            $notif->setUrl($this->generateUrl('administrator_book_block', ['token' => $bookBlock->getToken()]));

                        $notif->setUser($user);
                        $em->persist($notif);
                    }
                    $this->addFlash('success', "La validation de cette version a été terminé ");
                } else {
                    $validationRequest->setProgress(99);
                    $em->persist($version);
                    $this->addFlash('error', $test);
                    $em->flush();
                    return $this->redirectToRoute('validator_verify_version', ['token' => $token]);
                }
                $em->flush();
                return $this->redirectToRoute('validator_validation_requests');
            } else {
                $em->flush();
                $this->addFlash('info', 'Toutes les modifications ont été enregistrés');
                return $this->redirectToRoute('validator_verify_version', ['token' => $token]);
            }
        }

        return $this->render('@Main/Validator/verify.version.html.twig', array(
            'validationRequest' => $validationRequest,
            'block' => $bookBlock,
            'form' => $form->createView()));
    }

    private function verifyFigureAndTable($content)
    {
        $crawler = new Crawler($content);
        // first verify that all images has caption
        /** @var \DOMElement $imgDom */
        foreach ($crawler->filter('img') as $imgDom) {
            if ($imgDom->parentNode->nodeName != "figure")
                return "Chaque figure doit avoir une légende<br>
                <ul class='toastr-list'>
                    <li>Cliquer sur l'image</li>
                    <li>Cliquer option de l'image</li> 
                    <li>Cocher case 'Titre'</li>
                    <li>Entrer titre du figure</li>
                </ul>";
            elseif (strpos($imgDom->parentNode->textContent, "&&figureNumber&&")===false)
                return "Vous devez ajouter une marque de légende pour que le numéro du figure sera générer automatiquement<br>
                <ul class='toastr-list'>
                    <li>placer le curseur sur la légende de figure</li>
                    <li>cliquez sur le bouton vert en haut à droite de l'éditeur</li>
                </ul>";
        }
        // now  verify that all table has caption 2
        /** @var \DOMElement $tableDom */
        foreach ($crawler->filter('table') as $tableDom) {
            if ($tableDom->firstChild->nodeName != "caption")
                return "Vous devez ajouter une légende a chaque tableau <br>
                <ul class='toastr-list'>
                    <li>Cliquer sur le tableau</li>
                    <li>Cliquer propriétés du tableau</li> 
                    <li>Cocher case 'Titre'</li>
                    <li>Entrer titre du tableau </li>
                </ul>";
            elseif (strpos($tableDom->firstChild->textContent, "&&tableNumber&&")===false){
                return "Vous devez ajouter une marque de légende pour que le numéro du tableau sera générer automatiquement<br>
                <ul class='toastr-list'>
                    <li>placer le curseur sur la légende du tableau</li>
                    <li>cliquez sur le bouton bleu en haut à droite de l'éditeur</li>
                </ul>";
            }
        }
        return true;
    }

}

src/Webbook/MainBundle/Resources/views/Validator/index.html.twig
{% extends "MainBundle::layout.html.twig" %}
{% block classBody %}page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo{% endblock %}
{% block menu %}
    {{ parent() }}
{% endblock %}
{% block body %}
    <!-- BEGIN PAGE BASE CONTENT -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <i class="icon-home"></i>
                <a >Tableau de bord</a>
            </li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light">
                <div class="portlet-body">
                    <h1>Validateur Tableau de bord !</h1>
                </div>
            </div>
        </div>
    </div>
    <input type="hidden" value="" id="menuSelected" data-menu="page-index">

{% endblock %}

src/Webbook/MainBundle/Resources/views/Validator/verify.version.html.twig
{% extends '@Main/layout.html.twig' %}
{% block title %}
    {{ block.title }} - v {{ validationRequest.version.number }} - verification
{% endblock %}
{% block body %}
    <!-- BEGIN PAGE BASE CONTENT -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <i class="icon-home"></i>
                <a href="{{ url('validator_homepage') }}">Tableau de bord</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <i class="fa fa-check-square-o"></i>
                <a href="{{ url('validator_validation_requests') }}">Demandes de validation</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <span class="active">{{ block.title }} - v {{ validationRequest.version.number }} - verification </span>
            </li>
        </ul>
    </div>
    <div class="m-heading-1 border-green m-bordered row" style="margin-bottom: 17px;">
        <h2><i class="fa fa-check-square-o"></i> &nbsp; {{ block.title }} - version {{ validationRequest.version.number|number_format(1,'.',',') }} -
            verification </h2>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="pull-left" style="padding-top: 5px">
                        <button href="#animatedModal" type="button"  class="btn btn-sm blue btn-cmp-version" ><i class="fa fa-exchange"></i> Modification</button>
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse" data-original-title="reduire" title=""> </a>
                        <a href="" class="fullscreen" data-original-title="plein ecran" title=""> </a>
                    </div>
                </div>
                <div class="portlet-body col-md-12">

                    {{ form_start(form) }}
                    <div class="col-md-12">
                        <div class="slidershell">
                            <div class="sliderfill progress-bar progress-bar-striped active"></div>
                            <div class="slidertrack text-center"><strong id="ps-txt"> Progression </strong></div>
                            <div class="sliderthumb"></div>
                            <div class="slidervalue">0</div>
                            {{ form_widget(form.progress,{"attr":{"class":"progress-slider","data-min":validationRequest.progress}}) }}
                        </div>
                        {{ form_widget(form.version.content,{"attr":{"class":"tinyMince"}}) }}
                    </div>

                    <div class="col-md-12 text-center" style="margin-top: 10px">
                            <button class="btn blue " id="saveModification">
                                <i class="fa fa-download"></i>Enregistrer Modification
                            </button>
                    </div>
                    {{ form_widget(form._token) }}
                    {{ form_end(form, {'render_rest': false}) }}
                </div>
            </div>
        </div>
    </div>

    <!--DEMO01-->
    <div id="animatedModal" style="z-index: 99999">
        <div id="closebt-container" class="close-animatedModal">
            <img class="closebt" src="{{ asset('assets/img/closebt.svg') }}">
        </div>
        <div  id="animatedModal-content" class="modal-content">
            <h2 class="text-center bold font-green"> Comparaison de version </h2>
            <div class="col-md-12">
                <h4 class="col-md-6 text-center" style="color: grey">
                    <span class="col-md-5">Numéro version : <strong>{% if block.publishedVersion is not null  %}{{ block.publishedVersion.number|number_format(1,'.',',')  }}{% endif %}</strong></span>
                    <span class="col-md-7">&nbsp;&nbsp;- &nbsp; Crée par : <strong>{% if block.publishedVersion is not null  %} {{ block.publishedVersion.createdBy.fullName }} {% endif %}</strong></span>
                </h4>
                <h4 class="col-md-6 text-center" style="color: grey">
                    <span class="col-md-5">Numéro version : <strong>{{  validationRequest.version.number|number_format(1,'.',',')  }}</strong></span>
                    <span class="col-md-7">&nbsp;&nbsp;- &nbsp; Crée par : <strong>{{  validationRequest.version.createdBy.fullName }}</strong></span>
                </h4>
            </div>
            <div class="col-md-12" id="compare">

            </div>
        </div>
    </div>


    <div id="currentVersion" class="hidden">{% if block.publishedVersion is not null  %}{% spaceless %}{{ block.publishedVersion.content|convert_encoding('UTF-8', 'HTML-ENTITIES')}}{% endspaceless %}{% endif %}</div>
    <div id="newVersion" class="hidden">{% spaceless %}{{ validationRequest.version.content|convert_encoding('UTF-8', 'HTML-ENTITIES')}}{% endspaceless %}</div>
    <div id="fm-token" data-token="{{ validationRequest.version.token }}"></div>
    <input type="hidden" value="" id="menuSelected" data-menu="page-books">

{% endblock %}
{% block stylesheets %}
    <style>
        .toastr-list{
            list-style: decimal;
            padding-left: 15px;
        }
        #animatedModal-content{
            min-height:100px;
            margin-top: 50px;
            margin-bottom: 50px
        }
        #closebt-container {
            position: relative;
            width: 100%;
            text-align: center;
            margin-top: 40px;
        }
        .closebt{
            webkit-transition: all 0.2s;
            -moz-transition: all 0.2s;
            -ms-transition: all 0.2s;
            -o-transition: all 0.2s;
            transition: all 0.2s;
            cursor: pointer;
        }
        .closebt:hover{
            transform: rotate(90deg);
        }
        .mergely-canvas ,.mergely-margin{
            display: none;!important;
        }
        .CodeMirror-scroll{
            height: 400px!important;
        }
        .CodeMirror{
            height: auto!important;
        }
        .mergely.a.rhs {
            background-color: #cfc!important;
            color: #399839!important;
            border-color:  #399839!important;
            border-radius: 4px 0 0 4px!important;;
        }
        .mergely.c.lhs.start, .mergely.c.rhs.start,
        .mergely.c.lhs.end, .mergely.c.rhs.end{
            border: none!important;
        }
    </style>
    <link rel="stylesheet" href="{{ asset('assets/pages/css/author.block.version.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/pages/css/book.structure.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/global/plugins/mergely-3.4.4/lib/mergely.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/global/plugins/mergely-3.4.4/lib/codemirror.css') }}">
{% endblock %}
{% block javascripts %}
    <script type="text/javascript" src="{{ asset('assets/global/plugins/jquery.mjs.nestedSortable.js') }}"></script>
    <script type="text/javascript"
            src="{{ asset('assets/global/plugins/tinymce/js/tinymce/tinymce.min.js') }}"></script>
    <script type="text/javascript"
            src="{{ asset('assets/global/plugins/tinymce/js/tinymce/langs/fr_FR.js') }}"></script>
    <script src="{{ asset('assets/global/plugins/annimatedModal/animatedModal.js-master/animatedModal.min.js') }}"></script>
    <script src="{{ asset('assets/global/plugins/mergely-3.4.4/lib/codemirror.js') }}"></script>
    <script src="{{ asset('assets/global/plugins/mergely-3.4.4/lib/mergely.js') }}"></script>
    <script>
        $(document).ready(function () {
            tinymce.init({
                selector: '.tinyMince',  // change this value according to your HTML
                theme: 'modern',
                height: 400,
                table_default_attributes: {
                    cellspacing: '0',
                    width:200
                },
                setup:function (editor) {
                    editor.addButton('markF', {
                        tooltip: 'Marqueur de figures ( cliquer pour numéroté la figure) ',
                        image: '/assets/img/mark1.png',
                        onclick: function () {
                            editor.insertContent("Figure <small class='figureCaption' style='pointer-events: none'>&&figureNumber&&</small>&nbsp;:&nbsp;");
                        }
                    });
                    editor.addButton('markT', {
                        tooltip: 'Marqueur de tableaux ( cliquer pour numéroté le tableau)',
                        image: '/assets/img/mark2.png',
                        onclick: function () {
                            editor.insertContent("Tableau <small class='tableCaption' style='pointer-events: none'>&&tableNumber&&</small>&nbsp;:&nbsp;");
                        }
                    });
                },
                image_caption: true,
                plugins: [
                    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                    'searchreplace wordcount visualblocks visualchars code fullscreen',
                    'insertdatetime media nonbreaking save table contextmenu directionality',
                    'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc'
                ],
                image_advtab: true,
                file_browser_callback_types: 'file image media',
                file_browser_callback: function (field_name, url, type, win) {
                    var token = $('#fm-token').data('token');
                    tinymce.activeEditor.windowManager.open({
                        title: "Selectionneur du fichier",
                        url: Routing.generate('file_manager_load', {token: token, type: type}),
                        width: 320,
                        height: 240
                    }, {
                        window: win,
                        input: field_name,
                    });
                    return false;
                },
                toolbar1: "insertfile undo redo | styleselect | forecolor backcolor | | bold italic | alignleft aligncenter alignright alignjustify | " +
                "bullist numlist outdent indent | link image | print preview fullscreen | markT markF"
            });
            $('.btn-cmp-version').animatedModal({afterOpen:function() {
                $('#compare').mergely({
                    editor_width: 'calc(50% - 25px)',
                    editor_height: '100%',
                    sidebar:false,
                    ignorews:true,
                    cmsettings: {
                        readOnly: true,
                        lineNumbers: true ,
                        lineWrapping: true
                    },
                    lhs: function(setValue) {
                        setValue($('#currentVersion').text());
                    },
                    rhs: function(setValue) {
                        setValue($('#newVersion').text());
                    },
                    loaded:function () {
                        $('#animatedModal-content').css('height',$('.CodeMirror-scroll').height()+150)
                    }

                });
            }});
        })
    </script>
{% endblock %}